"""Added column 'disabled' for soft delete

Revision ID: bd91fdb42bba
Revises: a6e07ec20d38
Create Date: 2025-07-25 16:58:53.700035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd91fdb42bba'
down_revision: Union[str, Sequence[str], None] = 'a6e07ec20d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('disabled', sa.BOOLEAN(), nullable=False))
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'disabled')
    op.drop_column('posts', 'disabled')
    # ### end Alembic commands ###
