"""Removed cloumn 'is_added' from base model. Added column 'is_added' to usermodell 

Revision ID: cc364f1a07f4
Revises: 095ec926e9eb
Create Date: 2025-07-19 18:32:48.599958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc364f1a07f4'
down_revision: Union[str, Sequence[str], None] = '095ec926e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['id'])
    op.drop_column('posts', 'is_active')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('posts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
